[project]
name = "otbench"
version = "0.3.0"
description = ""
authors = [
    {name = "Christopher David Jellen"}
]
license = {text = "MIT License"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "lightgbm",
    "xarray",
    "netcdf4",
    "matplotlib",
    "requests",
    "astral",
    "cmocean",
    "tqdm",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
